### ISSUE TITLE
Variables names

### ISSUE THREAD

**Issue by danielcalvogonzalez** [budachst/ld382#3]
Hi, I've been trying to use your code but it seems there are some mistakes with variables names. Some of them are already translated into English while some of them remain in German.
I've been checking the code and I think I've fixed most of these errors.

Thank you

**Comment by budachst** [comment]
Can you be more specific?

**Comment by danielcalvogonzalez** [comment]
Of course, I can.

Let me start by saying that I'm using your code in Windows 10 although it
doesn't make a difference for the following mishap. Here I send you the
output:

Traceback (most recent call last):
  File "ld382a.py", line 311, in <module>
    dreamyLightDachboden.close()
NameError: name 'dreamyLightDachboden' is not defined

As you can see, there is a variable named "dreamyLightDachboden" that
doesn't exist.  I guess you mean "dreamyLightController". There are other
references to that variable as well.

Furthermore, and it makes sense, you use the modules "thread" and "syslog"
that are not included in python 3 for Windows 10 and you use the old print
syntax (w/o () ). Those are very easy to fix and as I said, it makes
totally sense.

By the way, I could use your program yesterday and it worked flawlessly.
You don't know how much time I've been looking for such a tool.

Thank you!!!! Danke!! Gracias!!!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-09 23:15 GMT+01:00 budachst <notifications@github.com>:

**Comment by budachst** [comment]
Changed the overlooked remnants of "historic" objects identifiers to more generic ones.
